### ISSUE TITLE
[Request] Support map/YAML flow input

### ISSUE THREAD

**Issue by jamieastley** [bitrise-io/go-steputils#23]
(Apologies in advance if this isn't the place to make such requests)

I'm currently maintaining an abandoned 3rd-party Bitrise step, and I've been trying to find a way to allow for the user to provide an optional list of key-value pairs for a particular input, eg:

```yaml
- my_step@1:
    inputs:
      - uri_actions:
          - button_text: Some text
            uri: www.google.com
          - button_text: Some text 2
            uri: www.google2.com
          - button_text: Some text 3
            uri: www.google3.com
```

However, maps aren't supported and can't be stored as a steps' environment variable.

Would it be possible to add support for this somehow? Even if at minimum, it's storing the `uri_actions` value as a stringified map which can then be parsed and handled on my steps' side in Go?

I'd make a PR and add this in myself if this wasn't my first venture into Go 🙂

**Comment by cathyharmon** [comment]
Hello,

I see that there were some ideas and suggestions discussed in Slack.  I am going to include and submit this as a feature request for review and consideration.

Thanks,
cathy

**Comment by godrei** [comment]
Hi @jamie1192 ,
sorry for my late response.

You can use the `|` yaml block style indicator to pass the stringified map:

```
  - my_step@1:
      inputs:
        - uri_actions: |-
            - button_text: Some text
              uri: www.google.com
            - button_text: Some text 2
              uri: www.google2.com
            - button_text: Some text 3
              uri: www.google3.com
```
